print("Getting to know you!")
yourName = input("What is your name? ")
hungry = input ("What is your favorite food? ")
music = input("What is your favorite music? ")
whereAreYou = input("Where are you? ")

print()

print("You are")
print(yourName)
print() 
print("You're probably hungry for")
print(hungry)
print()
print("You're probably listening to")
print (music)
print()
print ("You're probably living in the amazing")
print (whereAreYou)
print() 
print ("Have a great day!")